// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhwzs8YwLgnPzqi6UDOH4IQ7lYwPTEkU',
    appId: '1:413300061005:web:25a14a38449f637050bd04',
    messagingSenderId: '413300061005',
    projectId: 'e-shop-app-e4ce4',
    authDomain: 'e-shop-app-e4ce4.firebaseapp.com',
    storageBucket: 'e-shop-app-e4ce4.appspot.com',
    measurementId: 'G-XG73NDJVK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4mPSDboICVtNe2zBBsTuK69RjwYU9X0',
    appId: '1:413300061005:android:b65e1d0ce57d0b4f50bd04',
    messagingSenderId: '413300061005',
    projectId: 'e-shop-app-e4ce4',
    storageBucket: 'e-shop-app-e4ce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0I5WJoeq8LIKDwtpXPYTdbpiRn2nQLo',
    appId: '1:413300061005:ios:d2484de03e5d77be50bd04',
    messagingSenderId: '413300061005',
    projectId: 'e-shop-app-e4ce4',
    storageBucket: 'e-shop-app-e4ce4.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0I5WJoeq8LIKDwtpXPYTdbpiRn2nQLo',
    appId: '1:413300061005:ios:5b62b345f252eb9550bd04',
    messagingSenderId: '413300061005',
    projectId: 'e-shop-app-e4ce4',
    storageBucket: 'e-shop-app-e4ce4.appspot.com',
    iosBundleId: 'com.example.eShop.RunnerTests',
  );
}
